# Generated by Django 5.2.11 on 2026-02-09 18:29

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-release_date"]},
        ),
        migrations.AlterField(
            model_name="businessunit",
            name="debt_to_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Задолженность поставщику",
            ),
        ),
    ]
